# fly.toml app configuration file generated for scandinavian-name-correction on 2025-04-09T18:25:07+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'scandinavian-name-correction'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '8000'
  PYTHONUNBUFFERED = '1'
  DJANGO_SETTINGS_MODULE = 'fly_settings_override'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  max_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = "connections"
    hard_limit = 250
    soft_limit = 200

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"

[[vm]]
  memory = "8gb"
  cpu_kind = "shared"
  cpus = 4
